### PR TITLE
Ubiquitous operations preview

### PR DESCRIPTION
**Pull request by cowboyd**
There have been a lot of changes coming down the pike in effection as we refactor towards making all of the primitives just normal operations, but none of these have been tested in the bigtest/server codebase.

This aggregates the "operations" refactor into a single PR similar to #60 does so that we can preview the changes on an real codebase.

This includes:

* #57 implementing the core functionality of `fork`, and `join` as operations.
*  #62 which implements `monitor` as an operation.
* #63 for implementing the mailbox as two coordinating operations
* #65 Make typings encourage operation-centered thinking

### CODE REVIEW

**Comment by frontsidejack** [comment]
A preview package of this pull request has been released to NPM with the tag `operations-omnibus`.
You can try it out by running the following command:
```bash
$ npm install effection@operations-omnibus
```
or by updating your package.json to:
```bash
{
  "effection": "operations-omnibus"
}
```
Once the branch associated with this tag is deleted (usually once the PR is merged or closed), it will no longer be available. However, it currently references [effection@0.4.0-6db7e8c](https://www.npmjs.com/package/effection/v/0.4.0-6db7e8c) which will be available to install forever.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 6902052efb1bafa4d7ac9bc309be8ab44f5c918a
</p>

**Comment by frontsidejack** [comment]
A preview package of this pull request has been released to NPM with the tag `operations-omnibus`.
You can try it out by running the following command:
```bash
$ npm install effection@operations-omnibus
```
or by updating your package.json to:
```bash
{
  "effection": "operations-omnibus"
}
```
Once the branch associated with this tag is deleted (usually once the PR is merged or closed), it will no longer be available. However, it currently references [effection@0.4.0-11b36f4](https://www.npmjs.com/package/effection/v/0.4.0-11b36f4) which will be available to install forever.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 3a478fc870c5d958e1ec89819b1af555e7eff543
</p>

**Comment by frontsidejack** [comment]
A preview package of this pull request has been released to NPM with the tag `operations-omnibus`.
You can try it out by running the following command:
```bash
$ npm install effection@operations-omnibus
```
or by updating your package.json to:
```bash
{
  "effection": "operations-omnibus"
}
```
Once the branch associated with this tag is deleted (usually once the PR is merged or closed), it will no longer be available. However, it currently references [effection@0.4.0-4eaab4d](https://www.npmjs.com/package/effection/v/0.4.0-4eaab4d) which will be available to install forever.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against ea4c1ca00fabea0194cb2b97e13d16b3e06a721a
</p>

**Comment by jnicklas** [comment]
I think all of these PRs have been merged, right? Can we close this?

**Comment by cowboyd** [comment]
I think so!

**Pull request closed without merging**
