### PR TITLE
Next version preview

### PR DESCRIPTION
**Pull request by jnicklas**
This gathers multiple PRs so we can create a preview package based off-of them.

Includes:

#49 
#55 
#58

### CODE REVIEW

**Comment by frontsidejack** [comment]
A preview package of this pull request has been released to NPM with the tag `next`.
You can try it out by running the following command:
```bash
$ npm install effection@next
```
or by updating your package.json to:
```bash
{
  "effection": "next"
}
```
Once the branch associated with this tag is deleted (usually once the PR is merged or closed), it will no longer be available. However, it currently references [effection@0.4.0-e339a65](https://www.npmjs.com/package/effection/v/0.4.0-e339a65) which will be available to install forever.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f56aece795fdae50fb5f29baf9a2c71f52522316
</p>

**Comment by frontsidejack** [comment]
A preview package of this pull request has been released to NPM with the tag `next`.
You can try it out by running the following command:
```bash
$ npm install effection@next
```
or by updating your package.json to:
```bash
{
  "effection": "next"
}
```
Once the branch associated with this tag is deleted (usually once the PR is merged or closed), it will no longer be available. However, it currently references [effection@0.4.0-6f36fd9](https://www.npmjs.com/package/effection/v/0.4.0-6f36fd9) which will be available to install forever.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against a0b27e2b9136b87f5776f78dbd5216897610f49f
</p>

**Comment by frontsidejack** [comment]
A preview package of this pull request has been released to NPM with the tag `next`.
You can try it out by running the following command:
```bash
$ npm install effection@next
```
or by updating your package.json to:
```bash
{
  "effection": "next"
}
```
Once the branch associated with this tag is deleted (usually once the PR is merged or closed), it will no longer be available. However, it currently references [effection@0.4.0-a3f2e20](https://www.npmjs.com/package/effection/v/0.4.0-a3f2e20) which will be available to install forever.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 84e5d358383bb1a5962ccb7f4446d50b9523656a
</p>

**Comment by cowboyd** [comment]
superseded by #64

**Pull request closed without merging**
